/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HerbRouteRouteImport } from './routes/_herb/route'
import { Route as AnonRouteRouteImport } from './routes/_anon/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HerbDashboardRouteRouteImport } from './routes/_herb/dashboard/route'
import { Route as AnonAuthRouteRouteImport } from './routes/_anon/auth/route'

const HerbRouteRoute = HerbRouteRouteImport.update({
  id: '/_herb',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonRouteRoute = AnonRouteRouteImport.update({
  id: '/_anon',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HerbDashboardRouteRoute = HerbDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HerbRouteRoute,
} as any)
const AnonAuthRouteRoute = AnonAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AnonRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AnonAuthRouteRoute
  '/dashboard': typeof HerbDashboardRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AnonAuthRouteRoute
  '/dashboard': typeof HerbDashboardRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_anon': typeof AnonRouteRouteWithChildren
  '/_herb': typeof HerbRouteRouteWithChildren
  '/_anon/auth': typeof AnonAuthRouteRoute
  '/_herb/dashboard': typeof HerbDashboardRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_anon'
    | '/_herb'
    | '/_anon/auth'
    | '/_herb/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnonRouteRoute: typeof AnonRouteRouteWithChildren
  HerbRouteRoute: typeof HerbRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_herb': {
      id: '/_herb'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HerbRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_anon': {
      id: '/_anon'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AnonRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_herb/dashboard': {
      id: '/_herb/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof HerbDashboardRouteRouteImport
      parentRoute: typeof HerbRouteRoute
    }
    '/_anon/auth': {
      id: '/_anon/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AnonAuthRouteRouteImport
      parentRoute: typeof AnonRouteRoute
    }
  }
}

interface AnonRouteRouteChildren {
  AnonAuthRouteRoute: typeof AnonAuthRouteRoute
}

const AnonRouteRouteChildren: AnonRouteRouteChildren = {
  AnonAuthRouteRoute: AnonAuthRouteRoute,
}

const AnonRouteRouteWithChildren = AnonRouteRoute._addFileChildren(
  AnonRouteRouteChildren,
)

interface HerbRouteRouteChildren {
  HerbDashboardRouteRoute: typeof HerbDashboardRouteRoute
}

const HerbRouteRouteChildren: HerbRouteRouteChildren = {
  HerbDashboardRouteRoute: HerbDashboardRouteRoute,
}

const HerbRouteRouteWithChildren = HerbRouteRoute._addFileChildren(
  HerbRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnonRouteRoute: AnonRouteRouteWithChildren,
  HerbRouteRoute: HerbRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
