/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HerbRouteRouteImport } from './routes/_herb/route'
import { Route as AnonRouteRouteImport } from './routes/_anon/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HerbUsersRouteRouteImport } from './routes/_herb/users/route'
import { Route as HerbPackagesRouteRouteImport } from './routes/_herb/packages/route'
import { Route as HerbEmployeesRouteRouteImport } from './routes/_herb/employees/route'
import { Route as HerbDashboardRouteRouteImport } from './routes/_herb/dashboard/route'
import { Route as AnonAuthRouteRouteImport } from './routes/_anon/auth/route'

const HerbRouteRoute = HerbRouteRouteImport.update({
  id: '/_herb',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonRouteRoute = AnonRouteRouteImport.update({
  id: '/_anon',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HerbUsersRouteRoute = HerbUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => HerbRouteRoute,
} as any)
const HerbPackagesRouteRoute = HerbPackagesRouteRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => HerbRouteRoute,
} as any)
const HerbEmployeesRouteRoute = HerbEmployeesRouteRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => HerbRouteRoute,
} as any)
const HerbDashboardRouteRoute = HerbDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HerbRouteRoute,
} as any)
const AnonAuthRouteRoute = AnonAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AnonRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AnonAuthRouteRoute
  '/dashboard': typeof HerbDashboardRouteRoute
  '/employees': typeof HerbEmployeesRouteRoute
  '/packages': typeof HerbPackagesRouteRoute
  '/users': typeof HerbUsersRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AnonAuthRouteRoute
  '/dashboard': typeof HerbDashboardRouteRoute
  '/employees': typeof HerbEmployeesRouteRoute
  '/packages': typeof HerbPackagesRouteRoute
  '/users': typeof HerbUsersRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_anon': typeof AnonRouteRouteWithChildren
  '/_herb': typeof HerbRouteRouteWithChildren
  '/_anon/auth': typeof AnonAuthRouteRoute
  '/_herb/dashboard': typeof HerbDashboardRouteRoute
  '/_herb/employees': typeof HerbEmployeesRouteRoute
  '/_herb/packages': typeof HerbPackagesRouteRoute
  '/_herb/users': typeof HerbUsersRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/employees'
    | '/packages'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/dashboard' | '/employees' | '/packages' | '/users'
  id:
    | '__root__'
    | '/'
    | '/_anon'
    | '/_herb'
    | '/_anon/auth'
    | '/_herb/dashboard'
    | '/_herb/employees'
    | '/_herb/packages'
    | '/_herb/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnonRouteRoute: typeof AnonRouteRouteWithChildren
  HerbRouteRoute: typeof HerbRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_herb': {
      id: '/_herb'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HerbRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_anon': {
      id: '/_anon'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AnonRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_herb/users': {
      id: '/_herb/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof HerbUsersRouteRouteImport
      parentRoute: typeof HerbRouteRoute
    }
    '/_herb/packages': {
      id: '/_herb/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof HerbPackagesRouteRouteImport
      parentRoute: typeof HerbRouteRoute
    }
    '/_herb/employees': {
      id: '/_herb/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof HerbEmployeesRouteRouteImport
      parentRoute: typeof HerbRouteRoute
    }
    '/_herb/dashboard': {
      id: '/_herb/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof HerbDashboardRouteRouteImport
      parentRoute: typeof HerbRouteRoute
    }
    '/_anon/auth': {
      id: '/_anon/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AnonAuthRouteRouteImport
      parentRoute: typeof AnonRouteRoute
    }
  }
}

interface AnonRouteRouteChildren {
  AnonAuthRouteRoute: typeof AnonAuthRouteRoute
}

const AnonRouteRouteChildren: AnonRouteRouteChildren = {
  AnonAuthRouteRoute: AnonAuthRouteRoute,
}

const AnonRouteRouteWithChildren = AnonRouteRoute._addFileChildren(
  AnonRouteRouteChildren,
)

interface HerbRouteRouteChildren {
  HerbDashboardRouteRoute: typeof HerbDashboardRouteRoute
  HerbEmployeesRouteRoute: typeof HerbEmployeesRouteRoute
  HerbPackagesRouteRoute: typeof HerbPackagesRouteRoute
  HerbUsersRouteRoute: typeof HerbUsersRouteRoute
}

const HerbRouteRouteChildren: HerbRouteRouteChildren = {
  HerbDashboardRouteRoute: HerbDashboardRouteRoute,
  HerbEmployeesRouteRoute: HerbEmployeesRouteRoute,
  HerbPackagesRouteRoute: HerbPackagesRouteRoute,
  HerbUsersRouteRoute: HerbUsersRouteRoute,
}

const HerbRouteRouteWithChildren = HerbRouteRoute._addFileChildren(
  HerbRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnonRouteRoute: AnonRouteRouteWithChildren,
  HerbRouteRoute: HerbRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
